# Generated by Django 2.2.1 on 2019-06-20 21:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPorts',
            fields=[
                ('country', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('port', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.FloatField()),
                ('notes', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('date_creat', models.DateTimeField()),
                ('owner', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'all_ports',
            },
        ),
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(default='NA')),
            ],
            options={
                'db_table': 'communities',
            },
        ),
        migrations.CreateModel(
            name='Grids',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mstrid', models.FloatField()),
                ('f_p', models.FloatField()),
                ('f1_p', models.FloatField()),
                ('f2_p', models.FloatField()),
                ('f3_p', models.FloatField()),
                ('f4_p', models.FloatField()),
                ('grid0_1', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'amtgridv2sub0_1_fsh',
            },
        ),
        migrations.CreateModel(
            name='MarineTrafficData',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'marine_traffic_2010_data',
            },
        ),
        migrations.CreateModel(
            name='WorldBorder',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('area', models.IntegerField()),
                ('pop2005', models.IntegerField(verbose_name='Population 2005')),
                ('fips', models.CharField(max_length=2, verbose_name='FIPS Code')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 Digit ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 Digit ISO')),
                ('un', models.IntegerField(verbose_name='United Nations Code')),
                ('region', models.IntegerField(verbose_name='Region Code')),
                ('subregion', models.IntegerField(verbose_name='Sub-Region Code')),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'worldborders',
            },
        ),
    ]
