# Generated by Django 2.2.1 on 2019-05-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foliumApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worldborder',
            table='worldborders',
        ),
    ]
