# Generated by Django 2.2.1 on 2019-05-31 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliumApp', '0002_auto_20190531_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='id',
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
