# Generated by Django 2.2.1 on 2019-05-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foliumApp', '0003_auto_20190531_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='mpoly',
        ),
    ]
